# Generated by Django 3.2.16 on 2023-01-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cadastro",
            fields=[
                (
                    "cpf",
                    models.CharField(
                        help_text="Digite apenas números",
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        help_text="Use o formato: <em>DD/MM/AAAA</em>.",
                        verbose_name="data de nascimento",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="e-mail"),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em:"),
                ),
                ("matricula", models.CharField(max_length=9, verbose_name="matrícula")),
                (
                    "atendido",
                    models.BooleanField(default=False, verbose_name="atendido"),
                ),
            ],
            options={
                "verbose_name": "Cadastro",
                "verbose_name_plural": "Cadastros",
                "ordering": ["-criado_em"],
            },
        ),
    ]
