# Generated by Django 3.2.16 on 2023-01-23 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0002_alter_cadastro_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='cpf do dependente')),
                ('nome', models.CharField(max_length=100)),
                ('dt_nasc', models.DateField(verbose_name='data de nascimento do dependente')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
